**Authorization**

If Beneficial State Bank (“Bank”) approves this Application, Company agrees, with respect to all cards issued by Bank, to all the terms and conditions of all applicable agreements for the Business Credit Card requested and approved, as may be amended from time-to-time, including that certain Cardholder Agreement. Upon approval, a copy of each applicable agreement will be provided along with the card(s) issued to Company or with a letter informing Company that its business credit card account has been opened.

Company represents and warrants that the authorized signer(s) below has the authority to (i) designate initially the officers, members, managers, partners, agents, employees, or other representatives (collectively the “Representatives”) of Company to receive card(s) and (ii) to add or delete names of such Representatives or revise requested credit limits from time-to- time. Company requests Bank to issue in the name of Company, and to encode and validate Visa(s) each bearing, in addition to the name of Company, the name of the above Representatives, and such others as may be designated in writing by Company from time-to-time. Each such Representative(s) is authorized by Company to use the card(s). Company further agrees that Bank may, pursuant to Company’s instructions, allocate Company’s total credit limit by establishing individual credit limit(s) for each of the card(s).

<b>Important Information about procedures for opening a new account:</b> To help the government fight the funding of terrorism and money laundering activities, Federal law requires all financial institutions to obtain, verify, and record information that identifies each person or business entity that opens an account. What this means for you: When you open an account, we will ask for your name, street address, federal identification number, and other information that will allow us to identify your business entity or you. Company agrees to collect and verify the name, street address and social security or tax identification number of each individual that it has requested Bank to issue a card to, including all individuals identified on this Application. Company understands and acknowledges that Bank is relying on Company’s verification of all such information and its diligence of its employees and all individuals identified on this Application.

<ol type="1">
	<li>Each person(s) signing this Application certifies that
		<ol type="i">
			<li>s/he is at least 18 years old,</li>
			<li>s/he is authorized to execute and deliver this Application and to enter into the applicable agreements set forth or referred to herein on his/her behalf and on behalf of Applicant named on the Application,</li>
			<li>the loan or credit card requested under this Application is for business credit only and not for personal, family or household purposes,</li>
			<li>all information and documents submitted are true, correct and complete, and</li>
			<li>it has no non-discharged bankruptcy (one that is still unresolved).</li>
		</ol>
	</li>
	<li>Each person(s) signing this Application authorizes Bank, both now and in the future, to obtain consumer credit reports in his/her name(s) as individuals, to obtain business credit reports on Applicant, to make available to, and to obtain from other subsidiaries of Bank information related to both his/her and Applicant’s financial condition, and to provide credit bureaus and others with information about experiences with such person and Applicant.</li>
	<li>Each person(s) signing this Application is providing ‘written instructions’ to Bank under the Fair Credit Reporting Act authorizing Bank, both now and in the future, to obtain information from his/her credit profile or other information from a credit bureau. You further authorize Bank to obtain such information to confirm your identity and to help avoid fraudulent transactions in your name.</li>
	<li>The person(s) signing this Application acknowledges on behalf of himself/herself and Applicant that if additional information becomes available which would have influenced Bank’s decision to approve this Application prior to the closing of the transaction or the making of any advance, Bank reserves the right to withdraw such approval and to not make any advance.</li>
	<li>Applicant designates any person signing this Application to receive all communications from Bank and understands that Bank will retain this Application whether or not it is approved. Giving of notice to any one such person shall be sufficient to comply with Bank’s notice requirements.</li>
	<li>If Bank approves the Application, Applicant will be bound by the applicable agreements, including that certain Cardholder Agreement.</li>
	<li>Applicant understands additional information may be requested in connection with Bank’s review of the Application, and that failure to provide such additional information may result in denial of the Application.</li>
	<li>Applicant understands and acknowledges it may be required to deposit funds into an account maintained at Bank as collateral for any Indebtedness (as defined below) prior to Bank approval of the Application.</li>
	<li>Applicant agrees that Bank, Bank’s affiliates, agents and service providers may monitor and record telephone calls regarding Applicant’s account to assure the quality of service or for other reasons.</li>
	<li>Applicant agrees to, and has obtained the consent of each person listed above to whom a card is to be issued to, comply with the Beneficial State Bank Rewards Program Terms and Conditions.</li>
	<li>Our Communications with You: You agree that Bank, any of Bank’s affiliates, agents, independent contractors or service providers may monitor and record telephone calls regarding your banking services to assure the quality of our service or for other reasons. You expressly consent that Bank, any of Bank’s affiliates, agents, independent contractors or service providers may use written, electronic, or verbal means, or any other medium, as permitted by law and including, but not limited to, mail and facsimile, to contact you. Your consent includes, but is not limited to, contact by manual calling methods, prerecorded or artificial voice messages, text messages, emails and/or automatic telephone dialing systems. You agree that Bank, any of Bank’s affiliates, agents, independent contractors or service providers may contact you by using any email or any telephone number you provide, including a telephone number for a cellular phone or other wireless device, regardless of whether you incur any charges as a result.</li>
</ol>

By signing below, Applicant is signing up for an automatic payment from its Business Banking Account identified above and authorizes Bank to deduct from the Business Banking Account at the financial institution listed above for the monthly Business Credit Card payment. Applicant represents that the Business Banking Account is not a consumer account. Applicant understands this authorization will remain in effect until revoked by Applicant or Bank. To change or terminate this authorization, Applicant agrees to provide written notice to Bank at least 10 business days before the next payment due date, and Bank shall have reasonable time to act on any notice of termination given. Bank may also terminate this authorization for any reason. If this authorization is terminated for any reason, Applicant agrees to make payments by other methods permitted by the  Business Credit  Card agreement. Applicant understands all payments will be deducted on or around the 25th day after the billing date, unless otherwise disclosed on your Business Credit Card statement, and will appear on the deposit account statement. The payment deducted will be the Minimum Payment shown in the monthly Business Credit Card statement. Applicant understands that Applicant will still be responsible for the entire balance amount, any late fees, charges or other consequences of late or non-payment, whether because of insufficient funds, Applicant’s error or the error of Applicant’s financial institution. Even if Applicant has set up automatic payments, Applicant will be responsible for making monthly payments at the time and in the manner specified in the Welcome Letter and the Disclosure. Failure to timely make payments may result in a late charge, imposition of a default interest rate and/or the suspension or termination of advances under any line of credit, and Bank may pursue any other default remedies available to Bank under the Agreement and state law, including the right to declare  the entire unpaid principal balance of all loans to be immediately due and payable.
