  <style>
    .center {
      text-align: center;
    }
  </style>
<h2 class="center">Authorization</h2>

<p>By signing this Application, you, on behalf of Company and yourself, agree to the following:</p>
<p>If Beneficial State Bank (“Bank”) approves this Application, Company agrees, with respect to all cards issued by Bank, to all the terms and conditions of all applicable agreements for the Commercial Credit Card requested and approved, as may be amended from time-to-time, including the Commercial Credit Card Services Agreement and Cardholder Agreement. Upon approval, a copy of each applicable agreement will be provided along with the card(s) issued to Company or with a letter informing Company that its commercial credit card account has been opened.</p>
<p>Company represents and warrants that the authorized signer(s) below has the authority to (i) designate the officers, members, managers, partners, agents, employees, or other representatives (collectively the “Representatives”) of Company to receive card(s) and (ii) to add or delete names of such Representatives or revise requested credit limits from time-to-time. Company requests Bank to issue in the name of Company, and to encode and validate Visa(s) each bearing, in addition to the name of Company, the name of the above Representatives, and such others as may be designated in writing by Company from time-to-time. Each such Representative(s) is authorized by Company to use the card(s). Company further agrees that Bank may, pursuant to Company’s instructions, allocate Company’s total credit limit by establishing individual credit limit(s) for each of the card(s).</p>
<p><b>Important Information about procedures for opening a new account:</b> To help the government fight the funding of terrorism and money laundering activities, Federal law requires all financial institutions to obtain, verify, and record information that identifies each business entity that opens an account and the beneficial owners of the business entity (including those that have control of the business entity). What this means for you: When you open an account, we will ask for your name, street address, federal identification number, and other information that will allow us to identify your business entity and its beneficial owners and control persons. Company agrees to collect and verify the name, street address and social security or tax identification number of each individual that it has requested Bank to issue a card to, including all individuals identified on this Application. Company understands and acknowledges that Bank is relying on Company’s verification of all such information and its diligence of its employees and all individuals identified on this Application.</p>

<ol type="1">
	<li>Each person(s) signing this Application certifies that
		<ol type="i">
			<li>s/he is at least 18 years old,</li>
			<li>s/he is authorized to execute and deliver this Application and to enter into the applicable agreements set forth or referred to herein on of Company,</li>
			<li>the loan or credit card requested under this Application is for business credit only and not for personal, family or household purposes,</li>
			<li>all information and documents submitted are true, correct and complete, and</li>
			<li>the Company has no non-discharged bankruptcy (one that is still unresolved).</li>
		</ol>
	</li>
	<li>Bank is authorized, both now and in the future, to obtain business credit reports on Company, to make available to, and to obtain from other subsidiaries of Bank information related to Company’s financialcondition, and to provide credit bureaus and others with information about experiences with Company.</li>
	<li>Each person(s) signing this Application is providing ‘written instructions’ to Bank under the Fair Credit Reporting Act authorizing Bank, both now and in the future, to obtain credit reports and information from his/her credit profile or other information from credit bureaus. You further authorize Bank to obtain such information to confirm your identity and to help avoid fraudulent transactions in your name, and toprovide credit bureaus and others with information about experiences with you, including any defaults.</li>
	<li>The person(s) signing this Application acknowledges on behalf of himself/herself and Company that if additional information becomes available which would have influenced Bank’s decision to approve this Application prior to the closing of the transaction or the making of any advance, Bank reserves the right to withdraw such approval and to not make any advance.</li>
	<li>Company designates any person signing this Application to receive all communications from Bank on its behalf and understands that Bank will retain this Application whether or not it is approved. Giving of notice to any one such person shall be sufficient to comply with Bank’s notice requirements.</li>
	<li>If Bank approves the Application, Company will be bound by the applicable agreements, including that certain Commercial Credit Card Services Agreement.</li>
	<li>Company understands additional information may be requested in connection with Bank’s review of the Application, and that failure to provide such additional information may result in denial of the Application.</li>
	<li>Company understands and acknowledges it may be required to deposit funds into an account maintained at Bank as collateral for any and all amounts owed to Bank, including but not limited to all credit,advances, debts, obligations and liabilities of Company to Bank, under any agreement between Bank and Company, however arising, whether due or not due, absolute or contingent, liquidated or unliquidated (the “Indebtedness”), as well as any extensions, increases, modifications or renewals of such Indebtedness prior to Bank approval of the Application. Company agrees to grant Bank a first priority continuingsecurity interest in any and all present and future funds on deposit with Bank, and agrees to take such steps as Bank may reasonably require to perfect or protect such first priority security interest.</li>
	<li>Applicant agrees to, and has obtained the consent of each person listed above to whom a card is to be issued to, comply with the Beneficial State Bank Rewards Program Termsand Conditions.</li>
	<li><b>Our Communications with You:</b> You agree that Bank, any of Bank’s affiliates, agents, independent contractors or service providers may monitor and record telephone calls regarding your banking servicesto assure the quality of our service or for other reasons. You expressly consent that Bank, any of Bank’s affiliates, agents, independent contractors or service providers may use written, electronic, or verbal means, or any other medium, as permitted by law and including, but not limited to, email and facsimile, to contact you. Your consent includes, but is not limited to, contact by manual calling methods,prerecorded or artificial voice messages, text messages, emails and/or automatic telephone dialing systems. You agree that Bank, any of Bank’s affiliates, agents, independent contractors or service providersmay contact you by using any email or any telephone number you provide, including a telephone number for a cellular phone or other wireless device, regardless of whether you incur any charges as a result.</li>
</ol>
